### ISSUE TITLE
Concurent insert is not handled

### ISSUE THREAD

**Issue by tharry** [uberall/micronaut-distributed-lock#4]
If you have two or more threads(or processes, or servers) trying to lock in the same moment, one will be able too, and the rest will have exception thrown.

I'm not sure if this is intended or not?

**Comment by peh** [comment]
This is fully intended and thats why the Exception that would be thrown is [catched](https://github.com/uberall/micronaut-distributed-lock/blob/master/data-jdbc/src/main/java/com/uberall/MicronautDataJdbcLockService.java#L37) 
In fact it makes the JDBC implementation the "better" implementation as the redis implementation has an extremely small chance of not hitting such a case.

**Comment by tharry** [comment]
> This is fully intended and thats why the Exception that would be thrown is [catched](https://github.com/uberall/micronaut-distributed-lock/blob/master/data-jdbc/src/main/java/com/uberall/MicronautDataJdbcLockService.java#L37)
> In fact it makes the JDBC implementation the "better" implementation as the redis implementation has an extremely small chance of not hitting such a case.

Great @peh  - apologies as this was still present in previous version I was looking at.

**Comment by peh** [comment]
ah yeah we missed that in the first version :)
